# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1c47d812c146f2e31d54ea8a143a2fabc4897e4c433e597a3aa82d6ca6f1e0487b382f22345105fe092d2bb1c44340a2defa7686f9ac65aa7c8bb4abefc4523

test:
  secret_key_base: aadc9229c083be7626756218fecc2b3dbd4ee0c833a4c90b3272d3e5db07e82ea4e7eacafc2b841a08d638bb19131d05167fdb255ac96c29926d999801cfd6f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
